### ISSUE TITLE
Problems setting up the project

### ISSUE THREAD

**Issue by shaishavgandhi05** [hzsweers/CatchUp#109]
I tried importing CatchUp in Android Studio but seems like AS has a hard time figuring out the project structure. Modules don't show up the way they usually do in a multi-module project. 

Some info:
I was given two dialogs while importing the project. One to select the gradle wrapper, to which i selected the default gradle wrapper. The other was about which modules to include, the options being "CatchUp (root module)" and "buildSrc".

Am I missing something?

**Comment by hzsweers** [comment]
strange, I haven't re-set up the project in awhile. Can you add screenshots of what you're seeing?

**Comment by shaishavgandhi05** [comment]
Sure. Here are some screenshots. 

First dialog:
![screen shot 2018-03-25 at 1 28 24 pm](https://user-images.githubusercontent.com/2227639/37879623-b296d19a-3030-11e8-986e-33a0560cdeff.png)

Second dialog:
![screen shot 2018-03-25 at 1 28 39 pm](https://user-images.githubusercontent.com/2227639/37879625-bc33bb64-3030-11e8-9e34-0b631df0272a.png)

app build.gradle:
![screen shot 2018-03-25 at 1 29 13 pm](https://user-images.githubusercontent.com/2227639/37879628-cbc131ce-3030-11e8-8fbd-8efc563c7cbd.png)

**Comment by hzsweers** [comment]
I've seen that sometimes. Often just have to close and reopen android studio for it to link up correctly!

**Comment by shaishavgandhi05** [comment]
Hmmm. I tried that multiple times, didn't seem to work. Will check it out if reimporting works.

**Comment by PrashamTrivedi** [comment]
Have you got any success? If not, what about locating `settings.gradle` while opening the project. Directory based project never worked for me (Referring first screenshot). I used to clean `.idea` directory, `.iml` files and reopening any project by locating `settings.gradle`. Try this.

**Comment by hzsweers** [comment]
Going to close this out for now. Seems more of an issue with kotlin gradle script in general than this project in particulate

**Comment by Dimon94** [comment]
@PrashamTrivedi I find the solution in [this post](https://medium.com/@arturogdg/using-gradle-script-kotlin-for-android-d6cd58c80d60). 
- > Create an empty `build.gradle` file (with no content) at the root of the project.

- Create a  `settings.gradle`  at the root of the project and remove `settings.gradle.kst`.

Now you can try sync project and without problems.

### settings.gradle
```
rootProject.buildFileName = 'build.gradle.kts'

include ':app',
        ':libraries:gemoji',
        ':libraries:kotlinutil',
        ':libraries:retrofitconverters',
        ':libraries:third_party:bypass',
        ':libraries:tooling:spi-visualizer',
        ':libraries:util',
        ':service-api',
        ':service-registry:service-registry',
        ':service-registry:service-registry-annotations',
        ':service-registry:service-registry-compiler',
        ':services:designernews',
        ':services:dribbble',
        ':services:github',
        ':services:hackernews',
        ':services:imgur',
        ':services:medium',
        ':services:newsapi',
        ':services:producthunt',
        ':services:reddit',
        ':services:slashdot',
        ':services:unsplash',
        ':services:uplabs'

```
