### ISSUE TITLE
Gifs duplication issue when long pressing

### ISSUE THREAD

**Issue by Tunous** [hzsweers/CatchUp#67]
When long pressing on multiple gifs (one after another) the newly selected gif is copied to the position of previous as seen here:

![preview](https://thumbs.gfycat.com/DearestFixedGrosbeak-size_restricted.gif)

Running on Android 7.1

**Comment by hzsweers** [comment]
Yeah I've seen that before as well but not sure what causes it. Will take a look at the Plaid code to see if I'm missing something

**Comment by charlesdurham** [comment]
Seems like it might have something to do with Glide's bitmap caching, this hack fixes the issue:

```
 Glide.get(parent.context).bitmapPool.setSizeMultiplier(0f)
```

I also checked out Plaid and saw the same issue.

**Comment by hzsweers** [comment]
Interesting... do you know what about that workaround fixes it? I'm not familiar with the `setSizeMultiplier` method, or really bitmapPools in general. CC @NickButcher

**Comment by charlesdurham** [comment]
It makes the bitmap pool size 0 so no bitmaps will get reused (there may be a cleaner way of doing this in glide lol). Either way, it's not a viable solution, I was just using it to test my hunch.

**Comment by hzsweers** [comment]
OH, lol yeah interesting, wonder if it's worth reporting to Glide. I'll dig through their issue tracker for something related before I do

**Comment by charlesdurham** [comment]
I didn't find anything in their backlog, but there's a lot there so I could have missed something. I'll probably try to grab a simple repro case and log an issue (unless you find one in their backlog).

**Comment by charlesdurham** [comment]
https://github.com/bumptech/glide/issues/2526
