### ISSUE TITLE
Audit to match android kotlin style guide

### ISSUE THREAD

**Issue by hzsweers** [hzsweers/CatchUp#82]
I think the project mostly aligns with this already, but worth a look now that we have a style guide to point to - https://android.github.io/kotlin-guides/style.html

**Comment by Egorand** [comment]
I'm browsing through the codebase and can help with this ticket while I'm on it. I'd actually start with installing [ktlint](https://github.com/shyiko/ktlint), looks like it includes the Android style guide rules.

**Comment by hzsweers** [comment]
Yeah I've been thinking about setting up Spotless, which I think has a ktlint implementation

**Comment by Egorand** [comment]
Looks nice, haven't heard of Spotless before. Adding ktlint via the Gradle plugin actually didn't work for me, filed an issue: https://github.com/JLLeitschuh/ktlint-gradle/issues/47

**Comment by Egorand** [comment]
I noticed that the `buildscript` block inside the top-level Gradle build file is applied to `subprojects`, rather than just being declared on the top level - is there any specific reason for that? Looks like this setup won't allow doing `apply plugin` inside the `subprojects` block...

**Comment by hzsweers** [comment]
My memory is fuzzy, but iirc it was because there was a time that AGP/gradle had classloader issues on 3.0 that were only resolved by declaring all the plugins in the top level buildscript. I think it's been fixed since then though

**Comment by hzsweers** [comment]
I thiiiink this is mostly fine for now. Will follow up spotless later
